// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  $(function() {
    $("input").focus();
    return $("form").on("submit", function(event) {
      var movieData, searchTerm;
      event.preventDefault();
      searchTerm = $("input").val();
      movieData = $.ajax({
        url: "http://www.omdbapi.com",
        method: "get",
        data: {
          s: searchTerm
        },
        dataType: "json"
      });
      movieData.done(function(data) {
        var li, movie, _i, _len, _ref, _results;
        $("input").val("");
        $(".result").html("");
        _ref = data["Search"];
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          movie = _ref[_i];
          li = $("<li data-tuktuk='totals' data-imdbid='" + movie.imdbID + "'>" + movie.Title + "</li>");
          _results.push($(".result").append(li));
        }
        return _results;
      });
      return $(".result").delegate("li", "click", function(event) {
        var movieId, movieInfo;
        movieId = this.dataset.imdbid;
        movieInfo = $.ajax({
          url: "http://www.omdbapi.com",
          method: "get",
          data: {
            i: movieId
          },
          dataType: "json"
        });
        return movieInfo.done(function(data) {
          var imgSrc;
          imgSrc = data["Poster"];
          if (imgSrc === "N/A") {
            imgSrc = "http://www.mnit.ac.in/new/PortalProfile/images/faculty/noimage.jpg";
          }
          return $("img").attr("src", imgSrc);
        });
      });
    });
  });

}).call(this);
